### ISSUE TITLE
404 + 500 error handlers (fault)

### ISSUE THREAD

**Issue by TravelTimN** [TravelTimN/ci-milestone04-dcd#8]
For some reason in production mode, the 404 and 500 error pages aren't loading correctly ever since Flask-Blueprints were incorporated. Will come back and work on this at a later time.

@ignatiusukwuoma

**Comment by ignatiusukwuoma** [comment]
See http://flask.pocoo.org/docs/1.0/blueprints/#error-handlers

**Comment by TravelTimN** [comment]
I found this to work for the problem I'm having. It's working as intended now. https://stackoverflow.com/a/39770599

```
@errors.route("/<path:path>")
def path_error(path):
        return render_template("errors/404.html"), 404
```
